package models

import "go.mongodb.org/mongo-driver/bson/primitive"

// @notice Represents a beach clean-up proposal submitted by a user.
type Proposal struct {
	// @notice Proposal ID (automatically generated by MongoDB)
	Id primitive.ObjectID `json:"id" bson:"_id,omitempty"`

	// @notice Smart contract proposal ID (on-chain)
	ScId int64 `json:"scId"`

	// @notice List of contract addresses targeted by the proposal actions
	ScTargets []string `json:"scTargets"`

	// @notice ETH values sent with each contract call
	ScValues []int64 `json:"scValues"`

	// @notice Encoded function calldata for each action
	ScCalldatas []string `json:"scCalldatas"`

	// @notice Wallet address of the proposal creator
	Wallet string `json:"wallet"`

	// @notice Title or name of the proposal
	ProposalName string `json:"name" validate:"required"`

	// @notice Short description of the proposal with validation
	ProposalDescription string `json:"proposalDescription" validate:"required,min=8,max=256"`

	// @notice Name of the beach to be cleaned
	BeachName string `json:"beachName" validate:"required"`

	// @notice City where the beach is located
	City string `json:"city" validate:"required"`

	// @notice Province where the beach is located
	Province string `json:"province" validate:"required"`

	// @notice Google Maps link or coordinates of the beach
	Map string `json:"map" validate:"required"`

	// @notice URLs of proposal-related images (e.g., beach condition)
	Images []string `json:"images" validate:"required"`
}
