package models

import "go.mongodb.org/mongo-driver/bson/primitive"

// @notice Represents a river clean-up proposal submitted by a user.
type Proposal struct {
	// @notice Proposal ID (automatically generated by MongoDB)
	Id primitive.ObjectID `json:"id" bson:"_id,omitempty"`

	// @notice List of contract addresses targeted by the proposal actions
	ScTargets []string `json:"sctargets" validate:"required"`

	// @notice ETH values sent with each contract call
	ScValues []int64 `json:"scvalues" validate:"required"`

	// @notice Encoded function calldata for each action
	ScCalldatas []string `json:"sccalldatas" validate:"required"`

	// @notice Wallet address of the proposal creator
	Wallet string `json:"wallet" validate:"required"`

	// @notice Title or name of the proposal
	ProposalName string `json:"proposalname" validate:"required"`

	// @notice Short description of the proposal with validation
	ProposalDescription string `json:"proposaldescription" validate:"required,min=8,max=256"`

	// @notice Name of the river to be cleaned
	RiverName string `json:"rivername" validate:"required"`

	// @notice City where the river is located
	City string `json:"city" validate:"required"`

	// @notice Province where the river is located
	Province string `json:"province" validate:"required"`

	// @notice Google Maps link or coordinates of the river
	Map string `json:"map" validate:"required"`

	// @notice URLs of proposal-related images (e.g., river condition)
	Images []string `json:"images" validate:"required"`
}
